# Generated by Django 5.2.1 on 2025-06-11 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='board.board'),
        ),
    ]
